package com.example.backend.contract;

import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

/**
 * Base class for Contract Tests
 * Contract tests are generated by Spring Cloud Contract from .groovy files
 */
@SpringBootTest
@ActiveProfiles("test")
public abstract class ContractTestBase {
    // Base configuration for contract tests
    // Tests are auto-generated from contracts in src/test/resources/contracts/
}
